---

- name: install nginx
  package:
    name: nginx
    state: present

- name: create ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: configure nginx mime types
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: 0644

- name: initial configuration for certificates
  copy:
    src: "{{item.key}}"
    dest: /etc/nginx/{{item.value}}
    owner: root
    group: root
    force: no
    mode: 0640
  with_items:
    - { key: certificate.pem, value: "ssl/{{inventory_hostname}}.crt" }
    - { key: key.pem,         value: "ssl/{{inventory_hostname}}.key" }

- name: create diffie hellman ephemeral parameters for nginx
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: dhparam.pem file permission
  file:
    path: /etc/nginx/ssl/dhparam.pem
    owner: root
    group: root
    mode: 0640

- name: configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640
  notify: reload nginx

- name: install selinux config libs
  package:
    name: libsemanage-python
    state: present
  when: >
     ansible_distribution == 'CentOS'
     or ansible_distribution == 'Red Hat Enterprise Linux'
     or ansible_distribution == 'Scientific'

- name: allow httpd to act as reverse proxy
  become: yes
  seboolean:
    name: httpd_can_network_relay
    state: yes
    persistent: yes
  when: >
     ansible_distribution == 'CentOS'
     or ansible_distribution == 'Red Hat Enterprise Linux'
     or ansible_distribution == 'Scientific'

- name: start and enable nginx
  service:
    name={{item}}
    enabled=true
    state=started
  with_items:
    - nginx
